### ISSUE TITLE
stablecoin still stable

### ISSUE THREAD

**Issue by Waltermelon-lang** [CBD-platform/CBD-Contracts#1]
https://github.com/CBD-platform/CBD-Contracts/blob/c96e761b317d8c1f39ab1c9fab49257b957a6a6d/contracts/Purchase.sol#L48

I think it is good to have a check to ensure price of the stablecoin is above $0.95. Before allowing a transfer. 
Is it possible to make a free request (Uniswap or Chainlink) to get a stablecoin price in USD? 

What is your opinion?

**Comment by ravian-salman** [comment]
https://github.com/CBD-platform/CBD-Contracts/blob/5933ab8b298e006a3a5738fd7dd2b4c80ea8d942/contracts/Purchase.sol#L139-L141

No if stablecoin price is under 0.95$ user can not buy token

**Comment by Waltermelon-lang** [comment]
Thank you!
